name: Supabase DB push

on:
  push:
    branches:
      - main

jobs:
  db-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Postgres client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Build connection string
        id: conn
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          echo "CONN=postgresql://postgres:${SUPABASE_DB_PASSWORD}@db.utwhvnafvtardndgkbjn.supabase.co:5432/postgres" >> $GITHUB_ENV

      - name: Run SQL migrations
        run: |
          for file in $(ls db/migrations/*.sql | sort); do
            echo "Ejecutando $file"
            psql "$CONN" -f "$file"
          done
